### ISSUE TITLE
Allow start button to disappear on click

### ISSUE THREAD

**Issue by camerican** [ArnoldHundert/Wheel-of-Fortune#1]
To allow the start button to disappear on click, we can modify the `style.display` attribute.  Currently, the style.display is being set to an _undefined variable_ rather than the string value "none".

We can fix this as follows:

```
document.getElementById("startGame").style.display = "none";
```

**Comment by ArnoldHundert** [comment]
I had the exact line of code in my file......with one exception. mine ended in:
.display = none;        instead of
.display = "none";     I forgot the quotation marks. Now it works. Thanks Cam.
